---
version: '3.8'

services: 
 myjenkins: 
  image: jenkins:2.60.3
  ports: 
   - 5050:8080

 qaserver: 
  image: tomcat
  ports: 
   - 6060:8080
  links: 
   - myjenkins:jenkins


 prodserver: 
  image: tomcat
  ports: 
   - 7070:8080
  links: 
   - myjenkins:jenkins
          

...
