---
version: '3.8'
services: 
 db: 
  image: postgres
  environment: 
   POSTGRES_PASSWORD: admin
   POSTGRES_USER: myuser
   POSTGRES_DB: mydb

 adminer: 
  image: adminer
  ports: 
   - 9999:8080
  links: 
   - db:postgres
...
